# Generated by Django 4.1.2 on 2022-10-29 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='body',
            new_name='description',
        ),
    ]
