# Generated by Django 4.1.2 on 2022-10-30 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0002_rename_body_todo_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='date_created',
        ),
    ]
